// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_edemaere.Models;

namespace Mission06_edemaere.Migrations
{
    [DbContext(typeof(MoviesContext))]
    partial class MoviesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_edemaere.Models.MovieEntry", b =>
                {
                    b.Property<int>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntryId");

                    b.ToTable("Entries");

                    b.HasData(
                        new
                        {
                            EntryId = 1,
                            Category = "Sci-Fi",
                            Director = "Christopher Nolan",
                            Edited = false,
                            Notes = "It's lit bro",
                            Rating = "PG-13",
                            Title = "Inception",
                            Year = (short)2010
                        },
                        new
                        {
                            EntryId = 2,
                            Category = "Sci-Fi",
                            Director = "Christopher Nolan",
                            Edited = false,
                            Notes = "It's lit too",
                            Rating = "PG-13",
                            Title = "Interstellar",
                            Year = (short)2014
                        },
                        new
                        {
                            EntryId = 3,
                            Category = "Action",
                            Director = "Christopher Nolan",
                            Edited = false,
                            Notes = "Chris Nolan = Chad",
                            Rating = "PG-13",
                            Title = "The Dark Knight",
                            Year = (short)2008
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
